### ISSUE TITLE
[Switch] [Request] map touch controls to right stick (reward inside)

### ISSUE THREAD

**Issue by cucholix** [libretro/melonDS#63] opened 2020-04-27 17:05 UTC
Currently melonDS supports 2 modes for touch controls: touchscreen and mouse. 
It would be possible to map mouse to right stick and leave the following button setting?:
Right Stick Click = Close/Open DS lid
Right Stick = Touch movement
ZL = Touch screen Click
ZR = Mic Blow

Obviously it can be changed under options, so touchscreen controls still enabled.
I'm willing to put a $40 reward if someone can implement this.

**Comment by Awakened0** [comment] 2020-04-27 22:36
Why not other platforms too? This is basically a dupe of https://github.com/libretro/melonDS/issues/49

**Closed** 2020-04-27 22:39 UTC

**Comment by m4tsa** [comment] 2020-04-28 07:32
> 
> 
> Why not other platforms too? This is basically a dupe of #49

It currently relies on the libretro core rewrite which is only in the switch branch, I will port it all over when the aarch64 jit in a state where it can be disabled when compiling other targets. I have been holding off until I only have to maintain one branch

**Comment by Awakened0** [comment] 2020-04-28 07:54
Gotcha, thanks for the update!
