### ISSUE TITLE
Crash When firmware.bin.bak Not Present; Writes to firmware.bin Cause White Screen

### ISSUE THREAD

**Issue by Awakened0** [libretro/melonDS#56] opened 2019-08-26 00:10 UTC
I reported this in another closed issue, but figured I'd open an issue specifically for it, since others are reporting this in the libretro Discord. It seems 7fe9d50dc8a9141350215698e0caee58b5bdb8bc causes crashes during retro_load_game on some Win10 systems. I've tried getting a useful crash log out of it, but one dev mentioned that the makefile might not be setup to add debug symbols when building with DEBUG=1.

**Comment by bslenul** [comment] 2019-08-26 01:14
That was driving me crazy cause it finally worked after doing idk why :| But I manage to reproduce it and I think I finally found the cause, and it's pretty weird oO

Basically if you don't have firmware.bin.bak in your system folder it crashes (yes, the .bak!), simply make a copy of firmware.bin and rename it into firmware.bin.bak and... it just works.

**Comment by Awakened0** [comment] 2019-08-26 04:34
Thanks for looking into it! I was always deleting that file after running the older version of the core, so that's why I could never get the latest version to work. Now that there's a lead on the problem, hopefully it won't be hard to fix.

**Comment by Awakened0** [comment] 2019-08-26 05:01
I can get the latest build to work with the .bak file in system. But, if I change something in the firmware menu (like language), back out to let the system reboot, then close and restart RetroArch, the next time I try to load a game it gets stuck on a white screen. It seems doing that modifies the firmware.bin file and I have to restore it from the .bak to get it working again.

**Comment by Datamats** [comment] 2019-08-26 07:00
Able to build it with debug symbols and give me the crash report so I find out where it crashes? Not able to do it myself right now.

**Comment by Awakened0** [comment] 2019-08-26 08:29
When I tried building with DEBUG=1, the crash log didn't seem to contain anything more than it did with a normal build.

**Comment by bslenul** [comment] 2019-08-26 08:32
Hopefully I did this right: [MelonDS.zip](https://github.com/libretro/melonDS/files/3540199/MelonDS.zip)
180MB log file inside, I only ran it for a few seconds :p

**Comment by 7oxicshadow** [comment] 2019-08-26 11:43
I can confirm that this issue effects Linux aswell.

The firmware.bin.bak fix workaround fixes it.

**Comment by 7oxicshadow** [comment] 2019-08-26 12:03
It appears to fail in libretro.cpp (line 960).

If I am reading it correctly it looks like, data->buffer_ptr is uninitialised.

**Comment by 7oxicshadow** [comment] 2019-08-26 12:18
It fails at line 147 SPI.cpp.

Variable 'f' is null when it tries to write so it crashes.

It appears to crash because in line 227 of libretro.cpp the file handle request ends with 'true'. This is the "mustexist" flag. If the file does not exist it returns 0 and does not open a new file.

**Comment by Datamats** [comment] 2019-08-26 15:54
This commit should fix it on Linux and *most* likely Windows too 5d66040

**Comment by 7oxicshadow** [comment] 2019-08-26 16:03
Confirmed fixed on linux.

Unrelated. Is the OpenGL support still in development or should it work ok? I get a segfault when it is active. I will create a new bug if it should work.

**Comment by bslenul** [comment] 2019-08-26 16:20
Yup, the .bak issue is also fixed in W10!

**Comment by Datamats** [comment] 2019-08-26 17:20
closing this since people have reported it being fixed on both platforms.

also @7oxicshadow the OpenGL renderer should work fine for Linux, feel free to create an issue with information about your problem

**Closed by Datamats** 2019-08-26 17:20 UTC
