### ISSUE TITLE
melonDS runs better than melonDS Libretro and it's noticeable

### ISSUE THREAD

**Issue by hyarsan** [libretro/melonDS#19] opened 2017-12-09 11:47 UTC
I just noticed that melonDS runs better than the Libretro version. My guess is that the threaded 3D renderer hasn't been implemented yet. This is especially noticeable in the Level Select in New Super Mario Bros.

**Comment by Datamats** [comment] 2019-08-04 14:20
Closing since the issue is soon to be 2 years old, and the core has had a lot of progress since then (Including an option to enable threaded 3d renderer).

**Closed by Datamats** 2019-08-04 14:20 UTC
